
(async()=>{const root=document.getElementById('kse-evidence-preview');const response=await fetch('/api/profiles');if(!response.ok)throw Error('PROFILE_DATA_UNAVAILABLE');const data=await response.json();const select=root.querySelector('#kse-profile');const panel=root.querySelector('#kse-panel');const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let chosen=data.profiles.findIndex(p=>p.name==='Gdańsk Przyjaźń'&&p.voltage===110);if(chosen<0)chosen=0;let tab='investments',expanded=false;const reports=globalThis.KSEProfileReport;const drafts=new Map();const note=root.querySelector('#kse-user-note');const noteStatus=root.querySelector('#kse-note-status');let dirty=false;
data.profiles.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name+' · '+p.voltage+' kV';select.append(o)});
const save=()=>{if(window.openai?.setWidgetState)window.openai.setWidgetState({modelContent:{profile:data.profiles[chosen].name,voltage:data.profiles[chosen].voltage,view:tab},privateContent:{chosen,tab}}).catch(async()=>{})};
function render(){const p=data.profiles[chosen];select.value=chosen;root.querySelector('#kse-name').textContent=p.name;root.querySelector('#kse-voltage').textContent=p.voltage+' kV · według wykazu';root.querySelector('#kse-count').textContent=p.count;root.querySelector('#kse-mentions').textContent=p.links.length;root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));panel.setAttribute('aria-labelledby','kse-tab-'+tab);root.querySelector('#kse-opinion').textContent=reports.opinion(p);
root.querySelector('#kse-coverage').innerHTML='<details><summary>Pokrycie danych i braki</summary>'+reports.coverage(p).map(c=>'<p><strong>'+esc(c.section)+'</strong> — '+esc(c.description)+'</p>').join('')+'</details>';

if(tab==='investments'){const links=[...p.links].sort((a,b)=>Number(b.direct)-Number(a.direct));panel.innerHTML=links.length?links.slice(0,expanded?links.length:4).map(l=>{const h=data.headings[l.id];return '<article class="evidence"><span class="tag '+(l.direct?'sage':'sand')+'">'+(l.direct?'Nazwa przy opisie stacji':'Inny kontekst · do sprawdzenia')+'</span><span class="tag">'+esc(h.status||'Status wymaga przeglądu')+'</span><p>'+esc(h.title)+'</p><details><summary>Źródło i zakres dowodu</summary><p class="quiet">PSE · nagłówek publikacji · REPORTED · pobrano 18.09.2026</p><p class="quiet">'+esc(l.direct?'Rozpoznany kontekst stacji; tożsamość obiektu pozostaje niepotwierdzona.':'Wzmianka może dotyczyć linii, farmy lub złożonego zadania.')+'</p><p class="quiet">Lokalizator h4: '+h.positions.join(', ')+' · brak daty publikacji</p><a href="https://inwestycje.pse.pl/" target="_blank" rel="noopener noreferrer">Otwórz źródło ↗</a></details></article>'}).join(''):'<p class="empty">Brak dokładnej wzmianki o tej nazwie w przeglądanym indeksie. Sprawdź aliasy i inne źródła.</p>';if(links.length>4){const more=document.createElement('button');more.textContent=expanded?'Pokaż mniej':'Pokaż wszystkie ('+links.length+')';more.onclick=()=>{expanded=!expanded;render()};panel.append(more)}}
else if(tab==='pipeline'){
const projects=globalThis.KSEProfileProjects;
panel.innerHTML='<p class="quiet">Statusy i podmioty według PSE · stan '+esc(data.provenance.pipeline_source_date)+'. Moce z wykazu nie oznaczają rezerwy ani obciążenia sieci.</p>'+
'<label for="kse-project-status">Etap projektu</label><select id="kse-project-status">'+Object.entries(projects.labels).map(([key,label])=>'<option value="'+key+'">'+label+'</option>').join('')+'</select>'+
'<label for="kse-project-search">Szukaj podmiotu lub projektu</label><input id="kse-project-search" type="search" placeholder="Nazwa spółki lub obiektu">'+
'<p id="kse-project-results" role="status"></p><div id="kse-project-list"></div>'+
'<details><summary>Przypisy i oryginalny wykaz</summary><p>Wartości z dopiskami pozostają nieustalone. Znaczenie oznaczeń według publikacji:</p>'+data.pipeline_footnotes.map(f=>'<p>'+esc(f.marker)+' '+esc(f.meaning)+'</p>').join('')+
'<a href="'+esc(data.provenance.pipeline_source.url)+'" target="_blank" rel="noopener noreferrer">Otwórz wykaz PSE ↗</a></details>'+
'<p class="quiet">Umowa ani warunki przyłączenia nie potwierdzają uruchomienia. Liczba wpisów nie dowodzi konkurencji o wspólną infrastrukturę.</p>';
const status=panel.querySelector('#kse-project-status'),query=panel.querySelector('#kse-project-search');
const refresh=()=>{const rows=projects.filter(p.projects,status.value,query.value);panel.querySelector('#kse-project-results').textContent='Widoczne wpisy: '+rows.length+' z '+p.count;panel.querySelector('#kse-project-list').innerHTML=projects.cards(rows,data.provenance)};
status.onchange=refresh;query.oninput=refresh;refresh();}

else{panel.innerHTML='<div class="evidence"><span class="tag sand">Tożsamość</span><p>Potwierdzić, czy nazwa w wykazie i opis inwestycji odnoszą się do tego samego obiektu.</p></div><div class="evidence"><span class="tag sand">Zakres i czas</span><p>Zweryfikować poziom napięcia, etap zadania i jego związek z punktem przyłączenia.</p></div><div class="evidence"><span class="tag">Wykaz projektów</span><p>'+p.reviewCount+' wpisów z ostrzeżeniami parsera. Brak ostrzeżeń nie oznacza ręcznego potwierdzenia danych.</p></div>'}}

function rememberDraft(){drafts.set(data.profiles[chosen].id,{text:note.value,dirty});}
function loadNote(){const id=data.profiles[chosen].id;const draft=drafts.get(id);let saved;
try{saved=reports.readNote(window.localStorage,id)}catch{saved={text:'',state:'unavailable'}}
note.value=draft?draft.text:saved.text;dirty=draft?draft.dirty:false;
noteStatus.textContent=dirty?'Niezapisany szkic — zostanie dołączony do pobieranej karty.':saved.state==='unavailable'?'Pamięć przeglądarki niedostępna lub zapis nieczytelny. Pobierz kartę, aby zachować notatkę.':saved.state==='saved'?'Wczytano lokalną notatkę.':'Brak zapisanej notatki dla tego profilu.';
root.querySelector('#kse-report-preview').textContent='';}
function currentReport(){return reports.build(data,data.profiles[chosen].id,note.value,new Date().toISOString())}
note.addEventListener('input',()=>{dirty=true;rememberDraft();noteStatus.textContent='Niezapisany szkic — kliknij zapis lub pobierz kartę.';root.querySelector('#kse-report-preview').textContent=''});
root.querySelector('#kse-save-note').onclick=()=>{try{reports.saveNote(window.localStorage,data.profiles[chosen].id,note.value);dirty=false;rememberDraft();noteStatus.textContent='Notatka zapisana lokalnie.'}catch{noteStatus.textContent='Nie udało się zapisać notatki. Tekst pozostaje w polu; pobierz kartę.'}};
root.querySelector('#kse-preview-report').onclick=()=>{root.querySelector('#kse-report-preview').textContent=reports.markdown(currentReport())};
function download(kind){const report=currentReport();const text=kind==='json'?JSON.stringify(report,null,2):reports.markdown(report);const url=URL.createObjectURL(new Blob([text],{type:kind==='json'?'application/json;charset=utf-8':'text/markdown;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='kse-'+String(report.profile.id).replace(/[^a-zA-Z0-9_-]/g,'_')+'-'+report.generated_at.slice(0,10)+'.'+kind;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);noteStatus.textContent='Zlecono pobranie karty wraz z bieżącą notatką. Sprawdź pliki pobrane.';}
root.querySelector('#kse-export-md').onclick=()=>download('md');root.querySelector('#kse-export-json').onclick=()=>download('json');
window.addEventListener('beforeunload',e=>{if(dirty||[...drafts.values()].some(d=>d.dirty)){e.preventDefault();e.returnValue=''}});

function restore(state){const s=state?.privateContent;if(s&&Number.isInteger(s.chosen)&&data.profiles[s.chosen])chosen=s.chosen;if(['investments','pipeline','review'].includes(s?.tab))tab=s.tab;render();loadNote()}
select.onchange=()=>{rememberDraft();chosen=Number(select.value);expanded=false;render();loadNote();save()};root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();save()});restore(window.openai?.widgetState);window.addEventListener('openai:set_globals',e=>{if(e.detail?.globals?.widgetState){rememberDraft();restore(e.detail.globals.widgetState)}});
if(globalThis.Tweak){const design={accent:'#dde9dc',radius:18};const tweak=new Tweak({container:root,onChange:()=>{root.style.setProperty('--k-accent',design.accent);root.style.borderRadius=design.radius+'px'}});tweak.addColorPicker(design,'accent',{label:'Kolor akcentu'});tweak.addSlider(design,'radius',{label:'Zaokrąglenie',min:0,max:24,unit:'px'})}
})().catch(()=>{document.getElementById('kse-panel').textContent='Nie można wczytać spójnego zestawu danych. Sprawdź pliki źródłowe i odśwież stronę.';});
