
(async()=>{const root=document.getElementById('kse-evidence-preview');const response=await fetch('/api/profiles');if(!response.ok)throw Error('PROFILE_DATA_UNAVAILABLE');const data=await response.json();const select=root.querySelector('#kse-profile');const panel=root.querySelector('#kse-panel');const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let chosen=data.profiles.findIndex(p=>p.name==='Gdańsk Przyjaźń'&&p.voltage===110);if(chosen<0)chosen=0;let tab='investments',expanded=false;
data.profiles.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name+' · '+p.voltage+' kV';select.append(o)});
const save=()=>{if(window.openai?.setWidgetState)window.openai.setWidgetState({modelContent:{profile:data.profiles[chosen].name,voltage:data.profiles[chosen].voltage,view:tab},privateContent:{chosen,tab}}).catch(async()=>{})};
function render(){const p=data.profiles[chosen];select.value=chosen;root.querySelector('#kse-name').textContent=p.name;root.querySelector('#kse-voltage').textContent=p.voltage+' kV · według wykazu';root.querySelector('#kse-count').textContent=p.count;root.querySelector('#kse-mentions').textContent=p.links.length;root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));panel.setAttribute('aria-labelledby','kse-tab-'+tab);const direct=p.links.filter(l=>l.direct);root.querySelector('#kse-opinion').textContent=direct.length?'Są opisy zadań odnoszące się wprost do nazwy stacji. Ich status, zakres napięć i związek z wybranym punktem wymagają weryfikacji przed uznaniem modernizacji za korzystną przesłankę.':'Zebrane materiały nie wystarczają do określenia znaczenia inwestycji dla tego punktu. Brak dopasowania nie oznacza braku planów rozwoju.';
if(tab==='investments'){const links=[...p.links].sort((a,b)=>Number(b.direct)-Number(a.direct));panel.innerHTML=links.length?links.slice(0,expanded?links.length:4).map(l=>{const h=data.headings[l.id];return '<article class="evidence"><span class="tag '+(l.direct?'sage':'sand')+'">'+(l.direct?'Nazwa przy opisie stacji':'Inny kontekst · do sprawdzenia')+'</span><span class="tag">'+esc(h.status||'Status wymaga przeglądu')+'</span><p>'+esc(h.title)+'</p><details><summary>Źródło i zakres dowodu</summary><p class="quiet">PSE · nagłówek publikacji · REPORTED · pobrano 18.09.2026</p><p class="quiet">'+esc(l.direct?'Rozpoznany kontekst stacji; tożsamość obiektu pozostaje niepotwierdzona.':'Wzmianka może dotyczyć linii, farmy lub złożonego zadania.')+'</p><p class="quiet">Lokalizator h4: '+h.positions.join(', ')+' · brak daty publikacji</p><a href="https://inwestycje.pse.pl/" target="_blank" rel="noopener noreferrer">Otwórz źródło ↗</a></details></article>'}).join(''):'<p class="empty">Brak dokładnej wzmianki o tej nazwie w przeglądanym indeksie. Sprawdź aliasy i inne źródła.</p>';if(links.length>4){const more=document.createElement('button');more.textContent=expanded?'Pokaż mniej':'Pokaż wszystkie ('+links.length+')';more.onclick=()=>{expanded=!expanded;render()};panel.append(more)}}
else if(tab==='pipeline'){panel.innerHTML='<p class="quiet">Statusy według publikacji PSE · stan 31.07.2026</p>'+Object.entries(p.statuses).map(([s,n])=>'<div class="row"><span>'+esc(s)+'</span><strong>'+n+'</strong></div>').join('')+'<p class="quiet">Umowa ani warunki przyłączenia nie potwierdzają uruchomienia. Wiersze nie są sumowane jako moce konkurujące.</p>'}
else{panel.innerHTML='<div class="evidence"><span class="tag sand">Tożsamość</span><p>Potwierdzić, czy nazwa w wykazie i opis inwestycji odnoszą się do tego samego obiektu.</p></div><div class="evidence"><span class="tag sand">Zakres i czas</span><p>Zweryfikować poziom napięcia, etap zadania i jego związek z punktem przyłączenia.</p></div><div class="evidence"><span class="tag">Wykaz projektów</span><p>'+p.reviewCount+' wpisów z ostrzeżeniami parsera. Brak ostrzeżeń nie oznacza ręcznego potwierdzenia danych.</p></div>'}}
function restore(state){const s=state?.privateContent;if(s&&Number.isInteger(s.chosen)&&data.profiles[s.chosen])chosen=s.chosen;if(['investments','pipeline','review'].includes(s?.tab))tab=s.tab;render()}
select.onchange=()=>{chosen=Number(select.value);expanded=false;render();save()};root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();save()});restore(window.openai?.widgetState);window.addEventListener('openai:set_globals',e=>{if(e.detail?.globals?.widgetState)restore(e.detail.globals.widgetState)});
if(globalThis.Tweak){const design={accent:'#dde9dc',radius:18};const tweak=new Tweak({container:root,onChange:()=>{root.style.setProperty('--k-accent',design.accent);root.style.borderRadius=design.radius+'px'}});tweak.addColorPicker(design,'accent',{label:'Kolor akcentu'});tweak.addSlider(design,'radius',{label:'Zaokrąglenie',min:0,max:24,unit:'px'})}
})().catch(()=>{document.getElementById('kse-panel').textContent='Nie można wczytać spójnego zestawu danych. Sprawdź pliki źródłowe i odśwież stronę.';});
